// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable enable

namespace InstaCafe1.Models
{
    [Table("Cart_Status")]
    public partial class CartStatu
    {
        [Key]
        public int CartStatusId { get; set; }
        [StringLength(500)]
        public string? CartStatus { get; set; }
    }
}