// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace InstaCafe.Models
{
    public partial class Cart
    {
        [Key]
        [Column("Cart_Id")]
        public int CartId { get; set; }
        [Column("Product_Id")]
        public int ProductId { get; set; }
        [Column("Users_Id")]
        public int UsersId { get; set; }
        public int? CartStatusId { get; set; }

        [ForeignKey(nameof(ProductId))]
        [InverseProperty("Cart")]
        public virtual Product Product { get; set; }
    }
}