// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace InstaCafe.Models
{
    [Table("Cart_Status")]
    public partial class CartStatus
    {
        [Key]
        public int CartStatusId { get; set; }
        [Column("CartStatus")]
        [StringLength(500)]
        public string CartStatus1 { get; set; }
    }
}