// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable enable

namespace InstaCafe1.Models
{
    [Table("Category")]
    [Index(nameof(CategoryName), Name = "UQ__Category__B35EB4199D983D8F", IsUnique = true)]
    public partial class Category
    {
        public Category()
        {
            Products = new HashSet<Product>();
        }

        [Key]
        [Column("Category_Id")]
        public int CategoryId { get; set; }
        [Column("Category_Name")]
        [StringLength(255)]
        public string? CategoryName { get; set; }
        [Column("isActive")]
        public bool IsActive { get; set; }
        [Column("isDelete")]
        public bool IsDelete { get; set; }

        [InverseProperty(nameof(Product.Category))]
        public virtual ICollection<Product> Products { get; set; }
    }
}