// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace InstaCafe.Models
{
    public partial class Image
    {
        [Key]
        [Column("Image_ID")]
        public int ImageId { get; set; }
        [Required]
        [Column("Image_Title")]
        [StringLength(255)]
        public string ImageTitle { get; set; }
        [Required]
        [Column("Image_Pic")]
        public string ImagePic { get; set; }
    }
}