// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace InstaCafe.Models
{
    [Index(nameof(RoleName), Name = "UQ__Role__035DB7491D963308", IsUnique = true)]
    public partial class Role
    {
        public Role()
        {
            UsersRole = new HashSet<UsersRole>();
        }

        [Key]
        [Column("Role_Id")]
        public int RoleId { get; set; }
        [Column("Role_Name")]
        [StringLength(50)]
        public string RoleName { get; set; }

        [InverseProperty("Role")]
        public virtual ICollection<UsersRole> UsersRole { get; set; }
    }
}