// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable enable

namespace InstaCafe1.Models
{
    [Index(nameof(EmailId), Name = "UQ__Users__7ED91ACEFEDA43C9", IsUnique = true)]
    [Index(nameof(LastName), Name = "UQ__Users__8D0C18F7EB443455", IsUnique = true)]
    public partial class User
    {
        public User()
        {
            OrderDetails = new HashSet<OrderDetail>();
        }

        [Key]
        public int UserId { get; set; }
        [Column("First_Name")]
        [StringLength(100)]
        public string? FirstName { get; set; }
        [Column("Last_Name")]
        [StringLength(100)]
        public string? LastName { get; set; }
        public int? EmailId { get; set; }
        [StringLength(20)]
        public string? Password { get; set; }
        [Column("isActive")]
        public bool? IsActive { get; set; }
        [Column("isDelete")]
        public bool? IsDelete { get; set; }
        [Column("Created_Date", TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column("Modified_Date", TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }

        [InverseProperty(nameof(OrderDetail.User))]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}